# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-04 07:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('house', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('begin_date', models.DateTimeField(verbose_name='预订的起始时间')),
                ('end_date', models.DateTimeField(verbose_name='预订的结束时间')),
                ('days', models.SmallIntegerField(verbose_name='预订的总天数')),
                ('house_price', models.SmallIntegerField(verbose_name='房屋的单价')),
                ('amount', models.SmallIntegerField(verbose_name='订单的总金额')),
                ('comment', models.TextField(verbose_name='订单的评论信息或拒单原因')),
                ('status', models.CharField(choices=[('WAIT_ACCEPT', '待接单'), ('WAIT_PAYMENT', '待支付'), ('PAID', '已支付'), ('WAIT_COMMENT', '待评价'), ('COMPLETE', '已完成'), ('CANCELED', '已取消'), ('REJECTED', '已拒单')], default='WAIT_ACCEPT', max_length=50, verbose_name='订单状态')),
                ('house', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='house.House', verbose_name='房屋订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户订单')),
            ],
            options={
                'db_table': 'ih_order_info',
            },
        ),
    ]
